version: '3.9'

services:
  java-app:
    container_name: ackermann_function_java
    image: openjdk:17
    volumes:
      - .:/app
    working_dir: /app
    command: 
      - sh
      - -c
      - |
        javac Program.java &&
        java Program
