version: '3.9'

services:
  node:
    container_name: ackermann_function_node
    image: node:20
    volumes:
      - .:/app
    working_dir: /app
    command:
      - sh
      - -c
      - |
        node Program.js
