version: '3.9'

services:
  deno:
    container_name: ackermann_function_deno
    image: denoland/deno:1.13.2
    volumes:
      - .:/app
    working_dir: /app
    command:
      - sh
      - -c
      - |
        deno run --allow-read Program.ts
