version: '3.9'

services:
  scala:
    container_name: bubble_sort_scala
    image: hseeberger/scala-sbt:graalvm-ce-21.2.0-java11_1.5.5_2.13.6
    volumes:
      - .:/app
    working_dir: /app
    command:
      - sh
      - -c
      - |
        scala Program.scala
